### PR TITLE
Integrate embedded Aerospike

### PR DESCRIPTION
**Pull request by Aloren**
Main issue with tests was that I was not able to run them :), because they were pointing to some instance of Aerospike located on 52.41.32.83. I integrated testcontainers library, that gives an ability to setup docker container for tests. The only prerequisite for tests now is to have docker on machine.
While running tests locally I've found an issue with `AbstractPersonRepositoryIntegrationTests`: age index was commented out that was a reason for tests based on that index to fail with exception: index not found. 
Currently only 2 tests fail: `findsPersonInAgeRangeAndNameCorrectly` and `findMultipleFiltersFilterAndQualifier`. I'm not sure why they fail and how they can be fixed, cause I'm really new to Aerospike. Please advise. Thanks.

### CODE REVIEW

**Comment by Aloren** [comment]
I managed to fix the tests. Assertions were incorrect.

**Comment by Aloren** [comment]
@jboone100 could you please review?

**Comment by jboone100** [comment]
@Aloren thank you for doing this. It's a great addition.

**Comment by Aloren** [comment]
@jboone100 :) We are right now beginning to integrate spring-data-aerospike and faced quite a lot of missing functionality, so I will be doing more pull requests in this repo if you don't mind. Or I should stick to our company's fork?

**Comment by jboone100** [comment]
@Aloren we welcome your pull requests :-)

**Pull request merged**
